spring.application.name=bridged
spring.jpa.open-in-view=false 
 #database access to happen deliberately in your service/repository layer rather than potentially triggering lazy-loading queries while constructing the response.

spring.datasource.url=jdbc:postgresql://localhost:5432/bridged
spring.datasource.username=thisisanita
#have to add password later